pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "check-success=build"
    actions:
      merge:
        method: rebase
        strict: smart+fasttrack
        strict_method: rebase
